# Fable II
# Title ID: 4D5307F1
# Compat Tier: Playable

# TODO: license_mask from F0 research
# TODO: apu from F0 research
# TODO: apply_patches from F0 research
# TODO: clear_memory_page_table from F0 research
